services:
  pocketbase:
    container_name: pocketbase
    build:
      context: .
      dockerfile: Dockerfile_Pocketbase
    ports:
      - 8090:8090
    volumes:
      - ./pb/pb_data:/pb/pb_data
    healthcheck: #optional (recommended) since v0.10.0
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
